/*
 * Gate API v4
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Quotation Response
 */
public class AccountsResponse {
    public static final String SERIALIZED_NAME_CURRENCY = "currency";
    @SerializedName(SERIALIZED_NAME_CURRENCY)
    private String currency;

    public static final String SERIALIZED_NAME_AVAILABLE = "available";
    @SerializedName(SERIALIZED_NAME_AVAILABLE)
    private String available;

    public static final String SERIALIZED_NAME_LOCKED = "locked";
    @SerializedName(SERIALIZED_NAME_LOCKED)
    private String locked;

    public static final String SERIALIZED_NAME_TOKEN_ADDRESS = "token_address";
    @SerializedName(SERIALIZED_NAME_TOKEN_ADDRESS)
    private String tokenAddress;

    public static final String SERIALIZED_NAME_CHAIN = "chain";
    @SerializedName(SERIALIZED_NAME_CHAIN)
    private String chain;


    public AccountsResponse currency(String currency) {
        
        this.currency = currency;
        return this;
    }

     /**
     * Currency name
     * @return currency
    **/
    @javax.annotation.Nullable
    public String getCurrency() {
        return currency;
    }


    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public AccountsResponse available(String available) {
        
        this.available = available;
        return this;
    }

     /**
     * Available Balance
     * @return available
    **/
    @javax.annotation.Nullable
    public String getAvailable() {
        return available;
    }


    public void setAvailable(String available) {
        this.available = available;
    }

    public AccountsResponse locked(String locked) {
        
        this.locked = locked;
        return this;
    }

     /**
     * 锁定余额
     * @return locked
    **/
    @javax.annotation.Nullable
    public String getLocked() {
        return locked;
    }


    public void setLocked(String locked) {
        this.locked = locked;
    }

    public AccountsResponse tokenAddress(String tokenAddress) {
        
        this.tokenAddress = tokenAddress;
        return this;
    }

     /**
     * token 地址
     * @return tokenAddress
    **/
    @javax.annotation.Nullable
    public String getTokenAddress() {
        return tokenAddress;
    }


    public void setTokenAddress(String tokenAddress) {
        this.tokenAddress = tokenAddress;
    }

    public AccountsResponse chain(String chain) {
        
        this.chain = chain;
        return this;
    }

     /**
     * 区块链名称
     * @return chain
    **/
    @javax.annotation.Nullable
    public String getChain() {
        return chain;
    }


    public void setChain(String chain) {
        this.chain = chain;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccountsResponse accountsResponse = (AccountsResponse) o;
        return Objects.equals(this.currency, accountsResponse.currency) &&
                Objects.equals(this.available, accountsResponse.available) &&
                Objects.equals(this.locked, accountsResponse.locked) &&
                Objects.equals(this.tokenAddress, accountsResponse.tokenAddress) &&
                Objects.equals(this.chain, accountsResponse.chain);
    }

    @Override
    public int hashCode() {
        return Objects.hash(currency, available, locked, tokenAddress, chain);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AccountsResponse {\n");
        sb.append("      currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("      available: ").append(toIndentedString(available)).append("\n");
        sb.append("      locked: ").append(toIndentedString(locked)).append("\n");
        sb.append("      tokenAddress: ").append(toIndentedString(tokenAddress)).append("\n");
        sb.append("      chain: ").append(toIndentedString(chain)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

