/*
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.BrokerCommissionSubBrokerInfo;
import java.io.IOException;

/**
 * BrokerTransaction1
 */
public class BrokerTransaction1 {
    public static final String SERIALIZED_NAME_TRANSACTION_TIME = "transaction_time";
    @SerializedName(SERIALIZED_NAME_TRANSACTION_TIME)
    private Long transactionTime;

    public static final String SERIALIZED_NAME_USER_ID = "user_id";
    @SerializedName(SERIALIZED_NAME_USER_ID)
    private Long userId;

    public static final String SERIALIZED_NAME_GROUP_NAME = "group_name";
    @SerializedName(SERIALIZED_NAME_GROUP_NAME)
    private String groupName;

    public static final String SERIALIZED_NAME_FEE = "fee";
    @SerializedName(SERIALIZED_NAME_FEE)
    private String fee;

    public static final String SERIALIZED_NAME_CURRENCY_PAIR = "currency_pair";
    @SerializedName(SERIALIZED_NAME_CURRENCY_PAIR)
    private String currencyPair;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;

    public static final String SERIALIZED_NAME_FEE_ASSET = "fee_asset";
    @SerializedName(SERIALIZED_NAME_FEE_ASSET)
    private String feeAsset;

    public static final String SERIALIZED_NAME_SOURCE = "source";
    @SerializedName(SERIALIZED_NAME_SOURCE)
    private String source;

    public static final String SERIALIZED_NAME_SUB_BROKER_INFO = "sub_broker_info";
    @SerializedName(SERIALIZED_NAME_SUB_BROKER_INFO)
    private BrokerCommissionSubBrokerInfo subBrokerInfo;

    public static final String SERIALIZED_NAME_ALPHA_CONTRACT_ADDR = "alpha_contract_addr";
    @SerializedName(SERIALIZED_NAME_ALPHA_CONTRACT_ADDR)
    private String alphaContractAddr;


    public BrokerTransaction1 transactionTime(Long transactionTime) {
        
        this.transactionTime = transactionTime;
        return this;
    }

     /**
     * Transaction Time. (unix timestamp)
     * @return transactionTime
    **/
    @javax.annotation.Nullable
    public Long getTransactionTime() {
        return transactionTime;
    }


    public void setTransactionTime(Long transactionTime) {
        this.transactionTime = transactionTime;
    }

    public BrokerTransaction1 userId(Long userId) {
        
        this.userId = userId;
        return this;
    }

     /**
     * User ID
     * @return userId
    **/
    @javax.annotation.Nullable
    public Long getUserId() {
        return userId;
    }


    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public BrokerTransaction1 groupName(String groupName) {
        
        this.groupName = groupName;
        return this;
    }

     /**
     * Group name
     * @return groupName
    **/
    @javax.annotation.Nullable
    public String getGroupName() {
        return groupName;
    }


    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public BrokerTransaction1 fee(String fee) {
        
        this.fee = fee;
        return this;
    }

     /**
     * Fee amount (USDT)
     * @return fee
    **/
    @javax.annotation.Nullable
    public String getFee() {
        return fee;
    }


    public void setFee(String fee) {
        this.fee = fee;
    }

    public BrokerTransaction1 currencyPair(String currencyPair) {
        
        this.currencyPair = currencyPair;
        return this;
    }

     /**
     * Currency pair
     * @return currencyPair
    **/
    @javax.annotation.Nullable
    public String getCurrencyPair() {
        return currencyPair;
    }


    public void setCurrencyPair(String currencyPair) {
        this.currencyPair = currencyPair;
    }

    public BrokerTransaction1 amount(String amount) {
        
        this.amount = amount;
        return this;
    }

     /**
     * Transaction amount
     * @return amount
    **/
    @javax.annotation.Nullable
    public String getAmount() {
        return amount;
    }


    public void setAmount(String amount) {
        this.amount = amount;
    }

    public BrokerTransaction1 feeAsset(String feeAsset) {
        
        this.feeAsset = feeAsset;
        return this;
    }

     /**
     * Fee currency
     * @return feeAsset
    **/
    @javax.annotation.Nullable
    public String getFeeAsset() {
        return feeAsset;
    }


    public void setFeeAsset(String feeAsset) {
        this.feeAsset = feeAsset;
    }

    public BrokerTransaction1 source(String source) {
        
        this.source = source;
        return this;
    }

     /**
     * Commission transaction type: Spot, Futures, Options, Alpha
     * @return source
    **/
    @javax.annotation.Nullable
    public String getSource() {
        return source;
    }


    public void setSource(String source) {
        this.source = source;
    }

    public BrokerTransaction1 subBrokerInfo(BrokerCommissionSubBrokerInfo subBrokerInfo) {
        
        this.subBrokerInfo = subBrokerInfo;
        return this;
    }

     /**
     * Get subBrokerInfo
     * @return subBrokerInfo
    **/
    @javax.annotation.Nullable
    public BrokerCommissionSubBrokerInfo getSubBrokerInfo() {
        return subBrokerInfo;
    }


    public void setSubBrokerInfo(BrokerCommissionSubBrokerInfo subBrokerInfo) {
        this.subBrokerInfo = subBrokerInfo;
    }

    public BrokerTransaction1 alphaContractAddr(String alphaContractAddr) {
        
        this.alphaContractAddr = alphaContractAddr;
        return this;
    }

     /**
     * Alpha contract address
     * @return alphaContractAddr
    **/
    @javax.annotation.Nullable
    public String getAlphaContractAddr() {
        return alphaContractAddr;
    }


    public void setAlphaContractAddr(String alphaContractAddr) {
        this.alphaContractAddr = alphaContractAddr;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BrokerTransaction1 brokerTransaction1 = (BrokerTransaction1) o;
        return Objects.equals(this.transactionTime, brokerTransaction1.transactionTime) &&
                Objects.equals(this.userId, brokerTransaction1.userId) &&
                Objects.equals(this.groupName, brokerTransaction1.groupName) &&
                Objects.equals(this.fee, brokerTransaction1.fee) &&
                Objects.equals(this.currencyPair, brokerTransaction1.currencyPair) &&
                Objects.equals(this.amount, brokerTransaction1.amount) &&
                Objects.equals(this.feeAsset, brokerTransaction1.feeAsset) &&
                Objects.equals(this.source, brokerTransaction1.source) &&
                Objects.equals(this.subBrokerInfo, brokerTransaction1.subBrokerInfo) &&
                Objects.equals(this.alphaContractAddr, brokerTransaction1.alphaContractAddr);
    }

    @Override
    public int hashCode() {
        return Objects.hash(transactionTime, userId, groupName, fee, currencyPair, amount, feeAsset, source, subBrokerInfo, alphaContractAddr);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BrokerTransaction1 {\n");
        sb.append("      transactionTime: ").append(toIndentedString(transactionTime)).append("\n");
        sb.append("      userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("      groupName: ").append(toIndentedString(groupName)).append("\n");
        sb.append("      fee: ").append(toIndentedString(fee)).append("\n");
        sb.append("      currencyPair: ").append(toIndentedString(currencyPair)).append("\n");
        sb.append("      amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("      feeAsset: ").append(toIndentedString(feeAsset)).append("\n");
        sb.append("      source: ").append(toIndentedString(source)).append("\n");
        sb.append("      subBrokerInfo: ").append(toIndentedString(subBrokerInfo)).append("\n");
        sb.append("      alphaContractAddr: ").append(toIndentedString(alphaContractAddr)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

