/*
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Collateral record
 */
public class CollateralRecord {
    public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
    @SerializedName(SERIALIZED_NAME_ORDER_ID)
    private Long orderId;

    public static final String SERIALIZED_NAME_RECORD_ID = "record_id";
    @SerializedName(SERIALIZED_NAME_RECORD_ID)
    private Long recordId;

    public static final String SERIALIZED_NAME_BORROW_CURRENCY = "borrow_currency";
    @SerializedName(SERIALIZED_NAME_BORROW_CURRENCY)
    private String borrowCurrency;

    public static final String SERIALIZED_NAME_BORROW_AMOUNT = "borrow_amount";
    @SerializedName(SERIALIZED_NAME_BORROW_AMOUNT)
    private String borrowAmount;

    public static final String SERIALIZED_NAME_COLLATERAL_CURRENCY = "collateral_currency";
    @SerializedName(SERIALIZED_NAME_COLLATERAL_CURRENCY)
    private String collateralCurrency;

    public static final String SERIALIZED_NAME_BEFORE_COLLATERAL = "before_collateral";
    @SerializedName(SERIALIZED_NAME_BEFORE_COLLATERAL)
    private String beforeCollateral;

    public static final String SERIALIZED_NAME_AFTER_COLLATERAL = "after_collateral";
    @SerializedName(SERIALIZED_NAME_AFTER_COLLATERAL)
    private String afterCollateral;

    public static final String SERIALIZED_NAME_BEFORE_LTV = "before_ltv";
    @SerializedName(SERIALIZED_NAME_BEFORE_LTV)
    private String beforeLtv;

    public static final String SERIALIZED_NAME_AFTER_LTV = "after_ltv";
    @SerializedName(SERIALIZED_NAME_AFTER_LTV)
    private String afterLtv;

    public static final String SERIALIZED_NAME_OPERATE_TIME = "operate_time";
    @SerializedName(SERIALIZED_NAME_OPERATE_TIME)
    private Long operateTime;


    public CollateralRecord orderId(Long orderId) {
        
        this.orderId = orderId;
        return this;
    }

     /**
     * Order ID
     * @return orderId
    **/
    @javax.annotation.Nullable
    public Long getOrderId() {
        return orderId;
    }


    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public CollateralRecord recordId(Long recordId) {
        
        this.recordId = recordId;
        return this;
    }

     /**
     * Collateral record ID
     * @return recordId
    **/
    @javax.annotation.Nullable
    public Long getRecordId() {
        return recordId;
    }


    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public CollateralRecord borrowCurrency(String borrowCurrency) {
        
        this.borrowCurrency = borrowCurrency;
        return this;
    }

     /**
     * Borrowed currency
     * @return borrowCurrency
    **/
    @javax.annotation.Nullable
    public String getBorrowCurrency() {
        return borrowCurrency;
    }


    public void setBorrowCurrency(String borrowCurrency) {
        this.borrowCurrency = borrowCurrency;
    }

    public CollateralRecord borrowAmount(String borrowAmount) {
        
        this.borrowAmount = borrowAmount;
        return this;
    }

     /**
     * Borrowing amount
     * @return borrowAmount
    **/
    @javax.annotation.Nullable
    public String getBorrowAmount() {
        return borrowAmount;
    }


    public void setBorrowAmount(String borrowAmount) {
        this.borrowAmount = borrowAmount;
    }

    public CollateralRecord collateralCurrency(String collateralCurrency) {
        
        this.collateralCurrency = collateralCurrency;
        return this;
    }

     /**
     * Collateral
     * @return collateralCurrency
    **/
    @javax.annotation.Nullable
    public String getCollateralCurrency() {
        return collateralCurrency;
    }


    public void setCollateralCurrency(String collateralCurrency) {
        this.collateralCurrency = collateralCurrency;
    }

    public CollateralRecord beforeCollateral(String beforeCollateral) {
        
        this.beforeCollateral = beforeCollateral;
        return this;
    }

     /**
     * The collateral amount before adjustment
     * @return beforeCollateral
    **/
    @javax.annotation.Nullable
    public String getBeforeCollateral() {
        return beforeCollateral;
    }


    public void setBeforeCollateral(String beforeCollateral) {
        this.beforeCollateral = beforeCollateral;
    }

    public CollateralRecord afterCollateral(String afterCollateral) {
        
        this.afterCollateral = afterCollateral;
        return this;
    }

     /**
     * The collateral amount after adjustment
     * @return afterCollateral
    **/
    @javax.annotation.Nullable
    public String getAfterCollateral() {
        return afterCollateral;
    }


    public void setAfterCollateral(String afterCollateral) {
        this.afterCollateral = afterCollateral;
    }

    public CollateralRecord beforeLtv(String beforeLtv) {
        
        this.beforeLtv = beforeLtv;
        return this;
    }

     /**
     * The collateral ratio before adjustment
     * @return beforeLtv
    **/
    @javax.annotation.Nullable
    public String getBeforeLtv() {
        return beforeLtv;
    }


    public void setBeforeLtv(String beforeLtv) {
        this.beforeLtv = beforeLtv;
    }

    public CollateralRecord afterLtv(String afterLtv) {
        
        this.afterLtv = afterLtv;
        return this;
    }

     /**
     * The collateral ratio after adjustment
     * @return afterLtv
    **/
    @javax.annotation.Nullable
    public String getAfterLtv() {
        return afterLtv;
    }


    public void setAfterLtv(String afterLtv) {
        this.afterLtv = afterLtv;
    }

    public CollateralRecord operateTime(Long operateTime) {
        
        this.operateTime = operateTime;
        return this;
    }

     /**
     * Timestamp of the operation, in seconds
     * @return operateTime
    **/
    @javax.annotation.Nullable
    public Long getOperateTime() {
        return operateTime;
    }


    public void setOperateTime(Long operateTime) {
        this.operateTime = operateTime;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CollateralRecord collateralRecord = (CollateralRecord) o;
        return Objects.equals(this.orderId, collateralRecord.orderId) &&
                Objects.equals(this.recordId, collateralRecord.recordId) &&
                Objects.equals(this.borrowCurrency, collateralRecord.borrowCurrency) &&
                Objects.equals(this.borrowAmount, collateralRecord.borrowAmount) &&
                Objects.equals(this.collateralCurrency, collateralRecord.collateralCurrency) &&
                Objects.equals(this.beforeCollateral, collateralRecord.beforeCollateral) &&
                Objects.equals(this.afterCollateral, collateralRecord.afterCollateral) &&
                Objects.equals(this.beforeLtv, collateralRecord.beforeLtv) &&
                Objects.equals(this.afterLtv, collateralRecord.afterLtv) &&
                Objects.equals(this.operateTime, collateralRecord.operateTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(orderId, recordId, borrowCurrency, borrowAmount, collateralCurrency, beforeCollateral, afterCollateral, beforeLtv, afterLtv, operateTime);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CollateralRecord {\n");
        sb.append("      orderId: ").append(toIndentedString(orderId)).append("\n");
        sb.append("      recordId: ").append(toIndentedString(recordId)).append("\n");
        sb.append("      borrowCurrency: ").append(toIndentedString(borrowCurrency)).append("\n");
        sb.append("      borrowAmount: ").append(toIndentedString(borrowAmount)).append("\n");
        sb.append("      collateralCurrency: ").append(toIndentedString(collateralCurrency)).append("\n");
        sb.append("      beforeCollateral: ").append(toIndentedString(beforeCollateral)).append("\n");
        sb.append("      afterCollateral: ").append(toIndentedString(afterCollateral)).append("\n");
        sb.append("      beforeLtv: ").append(toIndentedString(beforeLtv)).append("\n");
        sb.append("      afterLtv: ").append(toIndentedString(afterLtv)).append("\n");
        sb.append("      operateTime: ").append(toIndentedString(operateTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

