/*
 * Gate API
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * MultiLoanRepayItem
 */
public class MultiLoanRepayItem {
    public static final String SERIALIZED_NAME_CURRENCY = "currency";
    @SerializedName(SERIALIZED_NAME_CURRENCY)
    private String currency;

    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private String amount;

    public static final String SERIALIZED_NAME_REPAID_ALL = "repaid_all";
    @SerializedName(SERIALIZED_NAME_REPAID_ALL)
    private Boolean repaidAll;


    public MultiLoanRepayItem currency(String currency) {
        
        this.currency = currency;
        return this;
    }

     /**
     * Repayment currency.
     * @return currency
    **/
    @javax.annotation.Nullable
    public String getCurrency() {
        return currency;
    }


    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public MultiLoanRepayItem amount(String amount) {
        
        this.amount = amount;
        return this;
    }

     /**
     * Size.
     * @return amount
    **/
    @javax.annotation.Nullable
    public String getAmount() {
        return amount;
    }


    public void setAmount(String amount) {
        this.amount = amount;
    }

    public MultiLoanRepayItem repaidAll(Boolean repaidAll) {
        
        this.repaidAll = repaidAll;
        return this;
    }

     /**
     * Repayment method, set to true for full repayment, false for partial repayment.
     * @return repaidAll
    **/
    @javax.annotation.Nullable
    public Boolean getRepaidAll() {
        return repaidAll;
    }


    public void setRepaidAll(Boolean repaidAll) {
        this.repaidAll = repaidAll;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MultiLoanRepayItem multiLoanRepayItem = (MultiLoanRepayItem) o;
        return Objects.equals(this.currency, multiLoanRepayItem.currency) &&
                Objects.equals(this.amount, multiLoanRepayItem.amount) &&
                Objects.equals(this.repaidAll, multiLoanRepayItem.repaidAll);
    }

    @Override
    public int hashCode() {
        return Objects.hash(currency, amount, repaidAll);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MultiLoanRepayItem {\n");
        sb.append("      currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("      amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("      repaidAll: ").append(toIndentedString(repaidAll)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

