/*
 * Gate API v4
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.gate.gateapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gate.gateapi.models.MultiCollateralRecordCurrency;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Multi-Collateral adjustment record.
 */
public class MultiCollateralRecord {
    public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
    @SerializedName(SERIALIZED_NAME_ORDER_ID)
    private Long orderId;

    public static final String SERIALIZED_NAME_RECORD_ID = "record_id";
    @SerializedName(SERIALIZED_NAME_RECORD_ID)
    private Long recordId;

    public static final String SERIALIZED_NAME_BEFORE_LTV = "before_ltv";
    @SerializedName(SERIALIZED_NAME_BEFORE_LTV)
    private String beforeLtv;

    public static final String SERIALIZED_NAME_AFTER_LTV = "after_ltv";
    @SerializedName(SERIALIZED_NAME_AFTER_LTV)
    private String afterLtv;

    public static final String SERIALIZED_NAME_OPERATE_TIME = "operate_time";
    @SerializedName(SERIALIZED_NAME_OPERATE_TIME)
    private Long operateTime;

    public static final String SERIALIZED_NAME_BORROW_CURRENCIES = "borrow_currencies";
    @SerializedName(SERIALIZED_NAME_BORROW_CURRENCIES)
    private List<MultiCollateralRecordCurrency> borrowCurrencies = null;

    public static final String SERIALIZED_NAME_COLLATERAL_CURRENCIES = "collateral_currencies";
    @SerializedName(SERIALIZED_NAME_COLLATERAL_CURRENCIES)
    private List<MultiCollateralRecordCurrency> collateralCurrencies = null;


    public MultiCollateralRecord orderId(Long orderId) {
        
        this.orderId = orderId;
        return this;
    }

     /**
     * Order ID
     * @return orderId
    **/
    @javax.annotation.Nullable
    public Long getOrderId() {
        return orderId;
    }


    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public MultiCollateralRecord recordId(Long recordId) {
        
        this.recordId = recordId;
        return this;
    }

     /**
     * Collateral record ID
     * @return recordId
    **/
    @javax.annotation.Nullable
    public Long getRecordId() {
        return recordId;
    }


    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public MultiCollateralRecord beforeLtv(String beforeLtv) {
        
        this.beforeLtv = beforeLtv;
        return this;
    }

     /**
     * The collateral ratio before adjustment
     * @return beforeLtv
    **/
    @javax.annotation.Nullable
    public String getBeforeLtv() {
        return beforeLtv;
    }


    public void setBeforeLtv(String beforeLtv) {
        this.beforeLtv = beforeLtv;
    }

    public MultiCollateralRecord afterLtv(String afterLtv) {
        
        this.afterLtv = afterLtv;
        return this;
    }

     /**
     * The collateral ratio before adjustment
     * @return afterLtv
    **/
    @javax.annotation.Nullable
    public String getAfterLtv() {
        return afterLtv;
    }


    public void setAfterLtv(String afterLtv) {
        this.afterLtv = afterLtv;
    }

    public MultiCollateralRecord operateTime(Long operateTime) {
        
        this.operateTime = operateTime;
        return this;
    }

     /**
     * Operation time, timestamp in seconds.
     * @return operateTime
    **/
    @javax.annotation.Nullable
    public Long getOperateTime() {
        return operateTime;
    }


    public void setOperateTime(Long operateTime) {
        this.operateTime = operateTime;
    }

    public MultiCollateralRecord borrowCurrencies(List<MultiCollateralRecordCurrency> borrowCurrencies) {
        
        this.borrowCurrencies = borrowCurrencies;
        return this;
    }

    public MultiCollateralRecord addBorrowCurrenciesItem(MultiCollateralRecordCurrency borrowCurrenciesItem) {
        if (this.borrowCurrencies == null) {
            this.borrowCurrencies = new ArrayList<>();
        }
        this.borrowCurrencies.add(borrowCurrenciesItem);
        return this;
    }

     /**
     * Borrowing Currency List
     * @return borrowCurrencies
    **/
    @javax.annotation.Nullable
    public List<MultiCollateralRecordCurrency> getBorrowCurrencies() {
        return borrowCurrencies;
    }


    public void setBorrowCurrencies(List<MultiCollateralRecordCurrency> borrowCurrencies) {
        this.borrowCurrencies = borrowCurrencies;
    }

    public MultiCollateralRecord collateralCurrencies(List<MultiCollateralRecordCurrency> collateralCurrencies) {
        
        this.collateralCurrencies = collateralCurrencies;
        return this;
    }

    public MultiCollateralRecord addCollateralCurrenciesItem(MultiCollateralRecordCurrency collateralCurrenciesItem) {
        if (this.collateralCurrencies == null) {
            this.collateralCurrencies = new ArrayList<>();
        }
        this.collateralCurrencies.add(collateralCurrenciesItem);
        return this;
    }

     /**
     * Collateral Currency List
     * @return collateralCurrencies
    **/
    @javax.annotation.Nullable
    public List<MultiCollateralRecordCurrency> getCollateralCurrencies() {
        return collateralCurrencies;
    }


    public void setCollateralCurrencies(List<MultiCollateralRecordCurrency> collateralCurrencies) {
        this.collateralCurrencies = collateralCurrencies;
    }
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MultiCollateralRecord multiCollateralRecord = (MultiCollateralRecord) o;
        return Objects.equals(this.orderId, multiCollateralRecord.orderId) &&
                Objects.equals(this.recordId, multiCollateralRecord.recordId) &&
                Objects.equals(this.beforeLtv, multiCollateralRecord.beforeLtv) &&
                Objects.equals(this.afterLtv, multiCollateralRecord.afterLtv) &&
                Objects.equals(this.operateTime, multiCollateralRecord.operateTime) &&
                Objects.equals(this.borrowCurrencies, multiCollateralRecord.borrowCurrencies) &&
                Objects.equals(this.collateralCurrencies, multiCollateralRecord.collateralCurrencies);
    }

    @Override
    public int hashCode() {
        return Objects.hash(orderId, recordId, beforeLtv, afterLtv, operateTime, borrowCurrencies, collateralCurrencies);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MultiCollateralRecord {\n");
        sb.append("      orderId: ").append(toIndentedString(orderId)).append("\n");
        sb.append("      recordId: ").append(toIndentedString(recordId)).append("\n");
        sb.append("      beforeLtv: ").append(toIndentedString(beforeLtv)).append("\n");
        sb.append("      afterLtv: ").append(toIndentedString(afterLtv)).append("\n");
        sb.append("      operateTime: ").append(toIndentedString(operateTime)).append("\n");
        sb.append("      borrowCurrencies: ").append(toIndentedString(borrowCurrencies)).append("\n");
        sb.append("      collateralCurrencies: ").append(toIndentedString(collateralCurrencies)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n        ");
    }

}

